name: Apply Terragrunt stack
on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: Path to terragrunt stack
        default: ./infrastructure/10 - first_module
      aws_region:
        description: Region for deployment
        default: us-east-1
jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.plan.exitcode }}
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: 0.42.5
      - uses: mdgreenwald/mozilla-sops-action@v1.4.0

      - name: Configure CICD AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - shell: pwsh
        env:
          SOPS_KMS_ARN: ${{ secrets.SOPS_KMS_ARN }}
        run: |
          Get-ChildItem -Filter *.enc.json -Recurse | %{ sops -d $_.FullName > ( $_.FullName -replace ".enc.json$", ".json" ) }

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Terragrunt plan
        id: plan
        working-directory: ${{ inputs.working-directory }}
        run: terragrunt plan  -detailed-exitcode -out=tfstate.plan -input=false

      - name: Terragrunt show plan
        working-directory: ${{ inputs.working-directory }}
        run: terragrunt show tfstate.plan

      - uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: ${{ inputs.working-directory }}/tfstate.plan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.plan.exitcode }}
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: 0.42.5
      - uses: mdgreenwald/mozilla-sops-action@v1.4.0

      - name: Configure CICD AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - shell: pwsh
        env:
          SOPS_KMS_ARN: ${{ secrets.SOPS_KMS_ARN }}
        run: |
          Get-ChildItem -Filter *.enc.json -Recurse | %{ sops -d $_.FullName > ( $_.FullName -replace ".enc.json$", ".json" ) }

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: ${{ inputs.working-directory }}

      - name: Terragrunt apply
        working-directory: ${{ inputs.working-directory }}
        run:  terragrunt apply tfstate.plan

