name: Apply Terragrunt stack
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: Path to terragrunt stack
        required: true
      aws_region:
        type: string
        description: Region for deployment
        required: true
      approve_environment:
        type: string
        description: Environment for select approvers
        required: true
      tg_environment:
        type: string
        required: true
        description: Json environment variables for terragrunt
jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}
    steps:
      - run: echo '${{ inputs.approve_environment }}'
#        env: ${{ fromJson(inputs.tg_environment) }}

      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: 0.42.5
      - uses: mdgreenwald/mozilla-sops-action@v1.4.0

      - name: Configure CICD AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - shell: pwsh
        env:
          SOPS_KMS_ARN: ${{ secrets.SOPS_KMS_ARN }}
        run: |
          Get-ChildItem -Filter *.enc.json -Recurse | %{ sops -d $_.FullName > ( $_.FullName -replace ".enc.json$", ".json" ) }

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Terragrunt plan
        id: plan
        env: ${{ fromJson(inputs.tg_environment) }}
        working-directory: ${{ inputs.working-directory }}
        run: terragrunt plan  -detailed-exitcode -out=tfstate.plan -input=false

      - name: Terragrunt show plan
        env: ${{ fromJson(inputs.tg_environment) }}
        if: ${{ steps.plan.outputs.exitcode == 2 }}
        working-directory: ${{ inputs.working-directory }}
        run: terragrunt show tfstate.plan

      - uses: actions/upload-artifact@v2
        env: ${{ fromJson(inputs.tg_environment) }}
        if: ${{ steps.plan.outputs.exitcode == 2 }}
        with:
          name: terraform-plan
          path: ${{ inputs.working-directory }}/tfstate.plan

  apply:
    needs: plan
    if: ${{ needs.plan.outputs.exitcode == 2 }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.approve_environment }}
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: 0.42.5
      - uses: mdgreenwald/mozilla-sops-action@v1.4.0

      - name: Configure CICD AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - shell: pwsh
        env:
          SOPS_KMS_ARN: ${{ secrets.SOPS_KMS_ARN }}
        run: |
          Get-ChildItem -Filter *.enc.json -Recurse | %{ sops -d $_.FullName > ( $_.FullName -replace ".enc.json$", ".json" ) }

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: ${{ inputs.working-directory }}

      - name: Terragrunt apply
        env: ${{ fromJson(inputs.tg_environment) }}
        working-directory: ${{ inputs.working-directory }}
        run:  terragrunt apply tfstate.plan

